### ISSUE TITLE
suggestion to restructure location of some OASYS widgets

### ISSUE THREAD

**Issue by srio** [oasys-kit/OASYS1#2]
I suggest a reorganization of the Oasys common widgets. Now we have

- Oasys Tools contains 1) Python Script, 2) Surface File Reader, 3) HDF5 File reader
- Syned Tools contain (among others) 1) Height Profile SImulator, 2) DABAM  Height Profile, 3) Surface FIle Merger

These utils are common Surface Metrology applications to be used with at least SRW and SHADOW

I think it is more reasonable to create a new entry at the top level (Oasys) called for example Oasys-Surfaces or Oasys-Metrology that will group: 
 1) Surface file Reader, 2)  Height Profile SImulator, 3) DABAM  Height Profile and 4) Surface FIle Merge

To be cleaner, I would place all the common objects (no widgets) to deal with that data in srxraylib/metrology (where we have now dabam, and it is a dependency from oasys1) and create a new add-on oasys-surfaces or oasys-metrology.

**Comment by lucarebuffi** [comment]
I agree. I'll do it asap.

**Comment by lucarebuffi** [comment]
I do not totally agree. Oasys is a general purpose set of widgets. Metrology is connected with common definitions for synchrotron radiation, so, in my opinion it belongs to Syned.
Then, moving those widget now, will have a major impact on APS user, since we have tens of workspaces that already used the widgets. I will move Surface file Reader from Oasys to Syned.
